In [3]:
!pip3 install -U ucimlrepo 

from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
apartment_for_rent_classified = fetch_ucirepo(id=555) 
  
# data (as pandas dataframes) 
X = apartment_for_rent_classified.data.features 
y = apartment_for_rent_classified.data.targets 
  
# metadata 
print(apartment_for_rent_classified.metadata) 
  
# variable information 
print(apartment_for_rent_classified.variables)

333.92s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: ucimlrepo in /Users/yuritziavila-robledo/anaconda3/envs/myNLP/lib/python3.8/site-packages (0.0.3)
{'uci_id': 555, 'name': 'Apartment for Rent Classified', 'repository_url': 'https://archive.ics.uci.edu/dataset/555/apartment+for+rent+classified', 'data_url': 'https://archive.ics.uci.edu/static/public/555/data.csv', 'abstract': 'This is a dataset of classified for apartments for rent in USA.\n', 'area': 'Business', 'tasks': ['Classification', 'Regression', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 10000, 'num_features': 21, 'feature_types': ['Categorical', 'Integer'], 'demographics': [], 'target_col': None, 'index_col': ['id'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2019, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C5X623', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': "The dataset contains of 10'000 or 100'000 rows and of 22 columns The data has been cleaned in the way that \r\ncolumn price and square_feet never is empty but the dataset is saved as it was created.\r\n\r\nCan be used for different machine learning tasks such as clustering, classification and also regression for the squares feet column", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'id = unique identifier of apartment\ncategory = category of classified\ntitle = title text of apartment\nbody = body text of apartment\namenities = like AC, basketball,cable, gym, internet access, pool, refrigerator etc.\nbathrooms = number of bathrooms\nbedrooms = number of bedrooms\ncurrency = price in current\nfee = fee\nhas_photo = photo of apartment\npets_allowed = what pets are allowed dogs/cats etc.\nprice = rental price of apartment\nprice_display = price converted into display for reader\nprice_type = price in USD\nsquare_feet = size of the apartment\naddress =  where the apartment is located\ncityname =  where the apartment is located\nstate =  where the apartment is located\nlatitude = where the apartment is located\nlongitude = where the apartment is located\nsource = origin of classified\ntime = when classified was created', 'citation': None}}
             name     role         type demographic description units  \
0              id       ID      Integer        None        None  None
1        category  Feature  Categorical        None        None  None
2           title  Feature  Categorical        None        None  None
3            body  Feature  Categorical        None        None  None
4       amenities  Feature  Categorical        None        None  None
5       bathrooms  Feature      Integer        None        None  None
6        bedrooms  Feature  Categorical        None        None  None
7        currency  Feature  Categorical        None        None  None
8             fee  Feature  Categorical        None        None  None
9       has_photo  Feature  Categorical        None        None  None
10   pets_allowed  Feature  Categorical        None        None  None
11          price  Feature      Integer        None        None  None
12  price_display  Feature      Integer        None        None  None
13     price_type  Feature  Categorical        None        None  None
14    square_feet  Feature  Categorical        None        None  None
15        address  Feature  Categorical        None        None  None
16       cityname  Feature  Categorical        None        None  None
17          state  Feature      Integer        None        None  None
18       latitude  Feature      Integer        None        None  None
19      longitude  Feature  Categorical        None        None  None
20         source  Feature      Integer        None        None  None
21           time  Feature  Categorical        None        None  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no

/Users/yuritziavila-robledo/anaconda3/envs/myNLP/lib/python3.8/site-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

In [14]:
import pandas as pd
# Example with low_memory=False
df = pd.read_csv('https://archive.ics.uci.edu/static/public/555/data.csv')
df.head()

/var/folders/4z/2hhh_brs3r7fjf6fj_zdz66w0000gn/T/ipykernel_2650/1541602833.py:3: DtypeWarning: Columns (0,5,6,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://archive.ics.uci.edu/static/public/555/data.csv')

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668640009,housing/rent/apartment,One BR 507 & 509 Esplanade,"This unit is located at 507 & 509 Esplanade, R...",NaN,1,1,USD,No,Thumbnail,...,2195,Monthly,542,507 509 Esplanade,Redondo Beach,CA,33.8520,-118.3759,RentLingo,1.577360e+09
1,5668639818,housing/rent/apartment,Three BR 146 Lochview Drive,"This unit is located at 146 Lochview Drive, Ne...",NaN,1.5,3,USD,No,Thumbnail,...,1250,Monthly,1500,146 Lochview Dr,Newport News,VA,37.0867,-76.4941,RentLingo,1.577360e+09
2,5668639686,housing/rent/apartment,Three BR 3101 Morningside Drive,This unit is located at 3101 Morningside Drive...,NaN,2,3,USD,No,Thumbnail,...,1395,Monthly,1650,3101 Morningside Dr,Raleigh,NC,35.8230,-78.6438,RentLingo,1.577360e+09
3,5668639659,housing/rent/apartment,Two BR 209 Aegean Way,"This unit is located at 209 Aegean Way, Vacavi...",NaN,1,2,USD,No,Thumbnail,...,1600,Monthly,820,209 Aegean Way,Vacaville,CA,38.3622,-121.9712,RentLingo,1.577360e+09
4,5668639374,housing/rent/apartment,One BR 4805 Marquette NE,"This unit is located at 4805 Marquette NE, Alb...",NaN,1,1,USD,No,Thumbnail,...,975,Monthly,624,4805 Marquette NE,Albuquerque,NM,35.1038,-106.6110,RentLingo,1.577360e+09

In [13]:

# Check for missing values
print(df.isnull().sum())

id                           0
category                     0
title                        0
body                         0
amenities                    0
bathrooms                    0
bedrooms                     0
fee                          0
has_photo                    0
pets_allowed                 0
price                        0
square_feet                  0
cityname                     0
state                        0
latitude_deg                 0
longitude_deg                0
source                       0
time                         0
street_address               0
city                         0
currency_1019                0
currency_Cats,Dogs           0
currency_USD                 0
price_type_Lawrence          0
price_type_Los Angeles       0
price_type_Monthly           0
price_type_Monthly|Weekly    0
price_type_VA                0
price_type_Weekly            0
dtype: int64

In [19]:
# Renamed columns for latitude/longitude degrees
df.rename(columns={'latitude': 'latitude_deg', 'longitude': 'longitude_deg'}, inplace=True)

# Ensured consistent data types
df['price'] = df['price'].astype(float)
df['time'] = pd.to_datetime(df['time'], unit='s')

# Dropped rows with missing values
df.dropna(inplace=True)  

#made my subset
subset_df = df.head(10)
print(subset_df)

               id                category                   title  \
80280  5187541828  housing/rent/apartment  Apartment for Sublease

                                                    body  \
80280  Ashburn 1 Beds Apartment for Sublet$1495/month...

                                               amenities bathrooms bedrooms  \
80280  AC,Cable or Satellite,Clubhouse,Dishwasher,Gym...         1        1

      fee  has_photo pets_allowed  ...  city currency_1019 currency_Cats,Dogs  \
80280  No  Thumbnail    Cats,Dogs  ...   206         False              False

      currency_USD  price_type_Lawrence  price_type_Los Angeles  \
80280         True                False                   False

      price_type_Monthly price_type_Monthly|Weekly price_type_VA  \
80280               True                     False         False

      price_type_Weekly
80280             False

[1 rows x 29 columns]